name: Deploy to Surge.sh

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "sender/**"
      - "tracker/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "latest"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: node build.js

      - name: Install Surge.sh
        run: npm install -g surge

      - name: Deploy to Surge.sh
        run: surge dist nikhilbadyal.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
