name: Build Resume
on:
  workflow_dispatch:
  push:
    paths:
      - assets/tex/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_resume:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.2.2
      - name: Compile Tex to PDF
        uses: xu-cheng/latex-action@3.3.0
        with:
          root_file: "assets/tex/NikhilBadyal.tex"
      - name: Move PDF to pdf directory
        run: |
          mv NikhilBadyal.pdf assets/pdfs/NikhilBadyal.pdf
      - name: Uploading artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Resume
          path: "assets/pdfs/NikhilBadyal.pdf"
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(TZ='Asia/Kolkata' date +"%d/%m/%Y-%H:%M:%S")" >> $GITHUB_OUTPUT
          echo "tag=$(TZ='Asia/Kolkata' date +%s)" >> $GITHUB_OUTPUT
      - name: Commit PDF file
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          branch: resumes
          skip_checkout: true
          file_pattern: "assets/pdfs/NikhilBadyal.pdf"
          commit_message: "🚀Resume Update ${{ steps.get-date.outputs.date }}"
          push_options: "--force"
      - name: Upload Build Artifact
        uses: ncipollo/release-action@main
        with:
          artifacts: "assets/tex/NikhilBadyal.tex,assets/pdfs/NikhilBadyal.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get-date.outputs.tag }}
          artifactErrorsFailBuild: true
