name: Deploy to Sender Worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "sender/**" # Trigger deployment for Sender when files in 'sender' folder change

jobs:
  deploy-sender:
    runs-on: ubuntu-latest
    name: Deploy Sender
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Set up Cloudflare credentials
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo "CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN" >> $GITHUB_ENV

      - name: Deploy Sender
        run: |
          cd sender
          DOMAIN=${{ secrets.CF_DOMAIN }} \
          WORKER_NAME=${{ secrets.CF_SENDER_WORKER }} \
          bash deploy.sh
